build:
  stage: build
  only:
  - tags
  before_script:
  - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
  script:
  - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG} .
  - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}

test:
  stage: test
  image: node:alpine
  script:
  - npm install
  - npm test
